apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  volumes:
    - name: emptydir-volume
      emptyDir: {}
    - name: nfs-volume
      nfs: 
        server: 192.168.146.128
        path: /mnt/shared
  containers:
    - name: main-container
      image: nginx:alpine
      command:
        - /bin/sh
        - -c
        - |
          echo "Hello from demo Pod" > /usr/share/nginx/html/index.html
          nginx -g 'daemon off;'
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: emptydir-volume
          mountPath: /usr/share/nginx/html
        - name: nfs-volume
          mountPath: /mnt/nfs
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:    
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10           
    - name: sidecar-container
      image: busybox
      command: ["/bin/sh", "-c" , "while true; do echo $(date) ' -  Sidecar logging'; sleep 5; done"]     
      resources:
        requests:
          memory: "16Mi"
          cpu: "100m"
        limits:
          memory: "32Mi"
          cpu: "200m"
      volumeMounts:
        - name: emptydir-volume
          mountPath: /mnt/shared    
