apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort    

